name: Sonarqube Test

on:
  push:
    branches: [ "sonarqube" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build con Maven
      run: mvn -B package --file pom.xml
      
    - name: Escaneo con SonarQube
      env:
        SONAR_HOST: "http://localhost:9000"
        SONAR_PROJECT_NAME: "my-sonar-project"
        SONAR_PROJECT_KEY: "my-sonar-project"
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # es un sonar poc, no hay problema con enseñar este token
      run: |
        mvn sonar:sonar \
          -Dsonar.host.url=$SONAR_HOST \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
          -Dsonar.projectName=$SONAR_PROJECT_NAME \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.maven.scanAll=true \
          --no-transfer-progress